### ISSUE TITLE
ổn định

### ISSUE THREAD

**Issue by thanhquang28** [yunkhngn/online-guestbook#2]
lên đại học cố gắng học thêm nhiều nữa nhé em, ở tuổi như em làm được như này là ok rồi
góp ý nho nhỏ là đặt tên thư mục vẫn còn sai. Và nên học thêm về typescript nếu em muốn theo về JS nhé.
Chúc em thành công.

**Comment by yunkhngn** [comment]
Em cảm ơn anh! 
Em vẫn đang học hỏi dần dần nên vẫn code chưa clean hẳn ạ! Typescript thì em đang học rồi anh ạ. Em sẽ cố gắng làm mấy cái ổn hơn.
